title: Dynohub
author: dynohub # name of site's author
email: dynohub@gmail.com # email of site's author
url: https://dynohub.github.io # root address of the site
description: > # DYNOHUB is nothing more than a place to dump all the random
  notes piling up on my hard drive. Mostly about cities. "Dynohub" was
  originally the trademark name of hubs for bicycles made by Sturmey Archer
  that generated power. This site is not about bicycle parts - here DYNOHUB is
  a metaphor for cities. Get it?

# These markdown options fix the autolinking of vimwiki links in github pages
markdown: CommonMarkGhPages
# see https://github.com/gjtorikian/commonmarker#parse-options
commonmark:
  options:
    - FOOTNOTES
    - SMART
  extensions:
    - autolink
    - strikethrough
    - table

permalink: /:slug.html

# favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
