title: Grannycart (work by Mark Torrey)
author: Mark Torrey # name of site's author
email: grannycart@protonmail.com # email of site's author
url: https://grannycart.net # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description:  Struggling to push home a rickety cartload of ideas rolling on a couple of squeaky wheels.

permalink: /:slug.html

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
goat_counter: "grannycart" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "grannycart.net" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

posts: _posts # location of posts for xml feed

kramdown: # need to disable smart typography for rss feed to work properly
  # This sets all site " and ' to typewriter style, which at least looks fine with my site/typeface:
  smart_quotes:               apos,apos,quot,quot
  # This sets emdashes (---) to use html &mdash;. And ellipse to html ellipse
  typographic_symbols:        {mdash: "&mdash;", hellip: "&hellip;"}

plugins:
  - jekyll-feed # google this for rss help
  - jekyll-seo-tag

# This tells jekyll-feed to generate a feed for the category of 'dopecentury' at feed/dopecentury.xml
feed:
  categories:
    - dopecentury
feed:
    posts_limit: 0 # set no limit on posts (otherwise default is 10)

