title: Grannycart (work by Mark Torrey)
author: Mark Torrey # name of site's author
email: grannycart@protonmail.com # email of site's author
url: http://grannycart.net # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description:  Struggling to push home a rickety cartload of ideas rolling on a couple of squeaky wheels.


# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# These markdown options fix the autolinking of vimwiki links in github pages
markdown: CommonMarkGhPages
# see https://github.com/gjtorikian/commonmarker#parse-options
commonmark:
  options:
    - FOOTNOTES
    - SMART
  extensions:
    - autolink
    - strikethrough
    - table

permalink: /:slug.html

favicon: "./favicon.ico" # relative path to site's favicon
goat_counter: "grannycart" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "grannycart.net" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
